#ifndef GUARD_CONSTANTS_DAY_NIGHT_H
#define GUARD_CONSTANTS_DAY_NIGHT_H

#define TIME_INVALID 0

#define TIME_PREDAWN 1
#define TIME_DAWN 7
#define TIME_NOON 13
#define TIME_DUSK 19
#define TIME_MIDNIGHT 25

#endif  // GUARD_CONSTANTS_DAY_NIGHT_H