ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Hey you! What's your name?\n"
    .string "…\p"
    .string "…\n"
    .string "{PLAYER} is it?\p"
    .string "Keep an eye out for\n"
    .string "strange POKéMON around here.$"

ViridianCity_PokemonCenter_1F_Text_Scientist::
    .string "Something strange is going on\n"
    .string "With this town.\p"
    .string "Strange people keep showing up\n"
    .string "and talk about strange places.$"
