ViridianCity_Text_CanCarryMonsAnywhere::
    .string "Those POKé BALLS at your waist!\n"
    .string "You have POKéMON, don't you?\p"
    .string "It's great that you can carry and\n"
    .string "use POKéMON anytime, anywhere.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "I wonder what's across this pond?$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "I saw a GOLDEN MAGIKARP!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "You want to know about the two\n"
    .string "kinds of caterpillar POKéMON?$"

ViridianCity_Text_OhOkayThen::
    .string "Oh, okay then!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "CATERPIE has no poison,\n"
    .string "but WEEDLE does.\p"
    .string "Watch that your POKéMON aren't\n"
    .string "stabbed by WEEDLE's POISON STING.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "Oh, Grandpa!\n"
    .string "Don't be so mean!\p"
    .string "I'm so sorry.\n"
    .string "He is a little tipsy.\p"
    .string "Give him a few minutes and return.\n"
    .string "He needs to digest a Persim Berry\p"
    .string "I just came back from the store$"


ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "See the Persim Berry is working!\n"
    .string "Persim Berries cure confusion.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "I absolutely forbid you from\n"
    .string "going through here!\p"
    .string "Not with those shoes!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Hic! Hicough!\n"
    .string "Oh my head!\p"
    .string "Hm?\n"
    .string "What is that red box you have?\p"
    .string "Ah, so you're working on your\n"
    .string "POKéDEX.\p"
    .string "Then let me give you a word of\n"
    .string "advice.\p"
    .string "Whenever you catch a POKéMON,\n"
    .string "the POKéDEX automatically updates\l"
    .string "its data.$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "Oh, I must of forgotten to teach you\n"
    .string "how to catch a POKéMON.\p"
    .string "Please, you should take this.$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "If there's something you don't\n"
    .string "understand, watch that.\p"
    .string "It will teach you about the basics\n"
    .string "of being a POKéMON TRAINER.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "I have a headache…$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Go away\n"
    .string "I have a headache…$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "Wahaha!\n"
    .string "It's my grandson on the show!\p"
    .string "Since he's the one doing the\n"
    .string "teaching, you're bound to learn.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… You're too busy to not even\n"
    .string "have the time for TEACHY TV…\p"
    .string "Time is money, and neither should\n"
    .string "be ill spent…$"

ViridianCity_Text_CitySign::
    .string "VIRIDIAN CITY \n"
    .string "The Eternally Green Paradise$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "TRAINER TIPS\p"
    .string "Catch POKéMON and expand your\n"
    .string "collection.\p"
    .string "The more you have, the easier it\n"
    .string "is to battle.$"

ViridianCity_Text_Ducksu::
    .string "BEHOLD!\n"
    .string "Oh my…\p"
    .string "BEHOLD!\n"
    .string "Oh my…\p"
    .string "BEHOLD!\n"
    .string "Oh my…\p"
    .string "BEHOLD!\n"
    .string "Oh my…\p"
    .string "BEHOLD!\n"
    .string "…$"

ViridianCity_Text_Ducksu2::
    .string "DUCKSU!$"

ViridianCity_Text_Ducksu3::
    .string "Warning! Beware of Ducksu!$"

ViridianCity_Text_GymSign::
    .string "VIRIDIAN CITY POKéMON GYM$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "VIRIDIAN GYM's doors are locked…$"

